# Generated by Django 4.1.13 on 2025-08-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'doctor')], default=1),
        ),
    ]
