# Generated by Django 4.1.13 on 2025-08-22 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenumber', models.CharField(max_length=11, unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientRegistration',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(2, 'doctor'), (1, 'admin')], default=1),
        ),
        migrations.AddField(
            model_name='patientreg',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
