# Generated by Django 4.1.13 on 2025-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(4, 'staff'), (3, 'patient'), (2, 'doctor'), (1, 'admin')], default=1),
        ),
    ]
