# Generated by Django 4.1.13 on 2025-08-25 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0007_staffreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctorregistration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctorregistration',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctorregistration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctorregistration',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='doctorregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='Updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='mobilenumber',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorregistration',
            name='regdate_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffreg',
            name='mobilenumber',
            field=models.CharField(max_length=10),
        ),
    ]
