# Generated by Django 4.1.13 on 2025-08-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0008_remove_doctorregistration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregistration',
            name='mobilenumber',
            field=models.CharField(max_length=10),
        ),
    ]
