# Generated by Django 4.1.13 on 2025-08-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0009_alter_doctorregistration_mobilenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientreg',
            old_name='regdate',
            new_name='regdate_at',
        ),
    ]
