# Generated by Django 4.1.13 on 2025-08-29 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0011_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobilenumber', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('Medicalhistory', models.TextField()),
                ('regdate_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.doctorregistration')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodpressure', models.CharField(max_length=250)),
                ('weight', models.CharField(max_length=250)),
                ('bloodsugar', models.CharField(max_length=250)),
                ('bodytemp', models.CharField(max_length=250)),
                ('prescription', models.TextField()),
                ('visitingdate_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pat_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='medical_histories', to='dekutmedic.addpatient')),
            ],
        ),
    ]
