# Generated by Django 4.1.13 on 2025-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0012_addpatient_medicalhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpatient',
            old_name='Medicalhistory',
            new_name='medicalhistory',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointmentnumber',
            new_name='appointmentnumber',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
