# Generated by Django 4.1.13 on 2025-09-01 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0013_rename_medicalhistory_addpatient_medicalhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referralnumber', models.IntegerField(default=0)),
                ('date_of_referral', models.CharField(max_length=250)),
                ('time_of_referral', models.CharField(max_length=250)),
                ('additional_msg', models.TextField(blank=True)),
                ('remark', models.CharField(default=0, max_length=250)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.doctorregistration')),
                ('hospital_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.hospital')),
                ('pat_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.patientreg')),
            ],
        ),
        migrations.DeleteModel(
            name='StaffReg',
        ),
    ]
