# Generated by Django 4.1.13 on 2025-09-01 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0014_hospital_referralappointment_delete_staffreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralappointment',
            name='hospital_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.hospital'),
        ),
        migrations.AlterField(
            model_name='referralappointment',
            name='pat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.patientreg'),
        ),
        migrations.AlterField(
            model_name='referralappointment',
            name='remark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
