# Generated by Django 4.1.13 on 2025-09-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0015_alter_referralappointment_hospital_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralappointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
