# Generated by Django 4.1.13 on 2025-09-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0018_alter_appointment_consultancy_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_by_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.patientreg'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='remark',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cover', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.patientreg')),
            ],
        ),
    ]
