# Generated by Django 4.1.13 on 2025-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0019_appointment_paid_by_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
