# Generated by Django 4.1.13 on 2025-09-08 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0021_alter_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='bloodsugar',
            new_name='diagnosis',
        ),
    ]
