# Generated by Django 4.1.13 on 2025-09-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0022_rename_bloodsugar_medicalhistory_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='remark',
            new_name='diagnosis',
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.CharField(default='', max_length=250),
        ),
    ]
