# Generated by Django 4.1.13 on 2025-09-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0023_rename_remark_appointment_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.patientreg'),
        ),
        migrations.AlterField(
            model_name='addpatient',
            name='medicalhistory',
            field=models.TextField(max_length=10),
        ),
    ]
