# Generated by Django 4.1.13 on 2025-09-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0025_alter_payment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpatient',
            name='mobilenumber',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dekutmedic.patientreg'),
        ),
    ]
