# Generated by Django 4.1.13 on 2025-09-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0026_alter_addpatient_mobilenumber_alter_payment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreg',
            name='mobilenumber',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dekutmedic.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
