# Generated by Django 4.1.13 on 2025-09-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0027_alter_patientreg_mobilenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
