# Generated by Django 4.1.13 on 2025-09-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0028_customuser_mobilenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorregistration',
            name='mobilenumber',
        ),
        migrations.RemoveField(
            model_name='patientreg',
            name='mobilenumber',
        ),
    ]
