# Generated by Django 4.1.13 on 2025-11-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0030_alter_customuser_user_type_staffregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pharmacy_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
