# Generated by Django 4.1.13 on 2025-11-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dekutmedic', '0031_appointment_pharmacy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultancy_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
